workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set up code signing
        script: |
          # Set up code signing for ad-hoc distribution
          keychain initialize
      - name: Get Flutter packages
        script: |
          flutter packages get
      - name: Build iOS for device
        script: |
          # Ensure we're building for device, not simulator
          flutter build ios --release --no-codesign
          # Verify the build is for device
          lipo -info build/ios/iphoneos/Runner.app/Runner || echo "Binary info not available"
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/**/*.ipa
    publishing:
      email:
        recipients:
          - matas@example.com
