workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up provisioning profiles
        script: |
          # Initialize keychain for code signing
          keychain initialize
      - name: Get Flutter packages
        script: |
          flutter packages get
      - name: Build iOS for physical device
        script: |
          # Clean any previous builds
          flutter clean
          flutter packages get
          # Explicitly build for iOS device (not simulator)
          flutter build ios --release --no-codesign --target-platform ios
          # Create a properly structured IPA
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../Runner-device.ipa Payload/
          # Verify architecture (should show arm64 for device)
          lipo -info Runner.app/Runner || echo "Could not read binary info"
    artifacts:
      - build/ios/iphoneos/Runner.app
      - Runner-device.ipa
    publishing:
      email:
        recipients:
          - matas@example.com
